### ISSUE TITLE
Time error

### ISSUE THREAD

**Issue by CungFu** [ess-uofc/ess-site#14]
https://essucalgary.netlify.app/events/frosh/

Time display error

**Comment by rjb75** [comment]
Added time display and changed the way date displays. Working on making times MST

**Comment by RatikKapoor** [comment]
@rjb75 Are the MST times done?

**Comment by rjb75** [comment]
@RatikKapoor MST times are updated in code, just working on how to integrate with forestry

**Comment by Dennull** [comment]
Closing outdated issues
