### ISSUE TITLE
Clean up sponsors

### ISSUE THREAD

**Issue by RatikKapoor** [ess-uofc/ess-site#22]
https://essucalgary.netlify.app/about/sponsors/

Match departments or teams layout to ensure continuity

**Comment by RatikKapoor** [comment]
Mostly done, need to remove sponsor.html and instead only use sponsors.html. Not enough content to justify another page.

**Comment by PixelPoncho** [comment]
**Missing Link**
Assuming that the Prep101 mentioned on the Sponsors page ([ess/prep101](https://essucalgary.com/about/sponsors/prep101/)) is the one here ([prep101.com](https://www.prep101.com/)), then the Sponsors page's "Website" button is missing the link/functionality to actually send users to there.

**Comment by RatikKapoor** [comment]
Add Haaziq's list of sponsors to page during edit

**Comment by Dennull** [comment]
Closing outdated issues
