### ISSUE TITLE
Store "Back To Website" Hyperlink broken

### ISSUE THREAD

**Issue by RatikKapoor** [ess-uofc/ess-site#29]
![image](https://user-images.githubusercontent.com/14501811/92202553-7ebd3900-ee3c-11ea-8c60-b7609561c2c3.png)

@rjb75 The link seems to point to `#` instead of `https://essucalgary.com`. Not sure what could have caused it to break but can you look into it?

**Comment by Dennull** [comment]
Closing outdated issues
