### ISSUE TITLE
Form on site for students to submit concerns

### ISSUE THREAD

**Issue by RatikKapoor** [ess-uofc/ess-site#4]
Formspree works well and can be integrated into Slack very efficiently. teamrelectric.ca has a working example of this.

**Comment by RatikKapoor** [comment]
@ewanmay Can you test and confirm that the contact form responses land directly in your email from Formspree? We may need to add Re-CAPTCHA in case there is too much spam

**Comment by Dennull** [comment]
Closing outdated issues
