### ISSUE TITLE
Store Issue? Terms and Conditions 404

### ISSUE THREAD

**Issue by PixelPoncho** [ess-uofc/ess-site#47]
I have absolutely no idea if this is intentional, but uuuh may be worth actually creating a terms and conditions for people who like to look over what they're agreeing to?
![image](https://user-images.githubusercontent.com/33527005/133683941-7d8fd6e0-b919-4bf9-9eee-9a223ea7ff88.png)

It may also be my browser settings, but the `Previous Page` hyperlink also does not work

**Comment by Dennull** [comment]
Closing outdated issues
